// B-231 (docs/16 par. 2): rejestr udokumentowanych endpointow. Schematy to schematy z @taktyl/contracts (zrodlo prawdy);
// test sprawdza, ze rejestr pokrywa dokladnie trasy zarejestrowane w Nest (w obie strony).
import {
  adminContentListQuerySchema,
  adminContentListSchema,
  adminContentResponseSchema,
  adminFaqSchema,
  adminMessageListQuerySchema,
  adminMessageListSchema,
  adminProductReviewsSchema,
  adminReviewListQuerySchema,
  adminReviewListSchema,
  contentCreateSchema,
  contentPatchSchema,
  descriptionPutSchema,
  descriptionResponseSchema,
  faqPutSchema,
  messagePatchSchema,
  reviewsPutSchema,
  adminSettingsSchema,
  settingsPatchSchema,
  adminPresetSchema,
  adminPresetsResponseSchema,
  adminProductDetailSchema,
  adminProductListQuerySchema,
  adminProductListSchema,
  priceHistoryResponseSchema,
  presetUpdateSchema,
  productCreateSchema,
  productPatchSchema,
  setPriceRequestSchema,
  setStockRequestSchema,
  stockMovementsResponseSchema,
  variantCreateSchema,
  variantPatchSchema,
  adminOrderDetailSchema,
  adminOrderListQuerySchema,
  adminOrderListSchema,
  adminUserSchema,
  auditListQuerySchema,
  auditListSchema,
  categoriesResponseSchema,
  colorsResponseSchema,
  completeSetQuerySchema,
  completeSetResponseSchema,
  createUserRequestSchema,
  facetsQuerySchema,
  facetsResponseSchema,
  listingQuerySchema,
  listingResponseSchema,
  loginRequestSchema,
  orderCreatedSchema,
  orderNoteRequestSchema,
  orderDetailSchema,
  orderListSchema,
  orderRequestSchema,
  orderTransitionRequestSchema,
  paymentSimulateRequestSchema,
  paymentSimulateResponseSchema,
  pickupPointsQuerySchema,
  pickupPointsResponseSchema,
  presetsResponseSchema,
  productQuerySchema,
  productSchema,
  publicShopSettingsSchema,
  quoteRequestSchema,
  quoteResponseSchema,
  rulesSchema,
  searchQuerySchema,
  searchResponseSchema,
  sessionResponseSchema,
  shippingEstimateQuerySchema,
  shippingEstimateResponseSchema,
  switchesResponseSchema,
  updateUserRequestSchema,
  updateUserResponseSchema,
  usersResponseSchema,
  revalidateRequestSchema,
  revalidateResponseSchema,
  type Role,
} from "@taktyl/contracts";
import type { z } from "zod";

export interface HeaderDoc {
  name: string;
  required: boolean;
  description: string;
}

export interface RouteDoc {
  method: "get" | "post" | "put" | "patch" | "delete";
  /** Sciezka w stylu OpenAPI, z prefiksem /v1 (poza health). */
  path: string;
  summary: string;
  tag: string;
  /** Funkcje i zadania z docs/16 par. 2 (kolumna ID). */
  ids: string[];
  query?: z.ZodType;
  body?: z.ZodType;
  pathParams?: Record<string, string>;
  headers?: HeaderDoc[];
  /** Kod odpowiedzi sukcesu, schemat odpowiedzi. */
  success: { status: number; schema?: z.ZodType; description: string };
  /** Dodatkowe kody bledow poza wspolnymi (docs/16 par. 2). */
  errors?: { status: number; code: string }[];
  noStore?: boolean;
  /** orderToken = X-Order-Token (publiczne zamowienia); session = ciasteczko sesji backpanelu (+ X-CSRF-Token przy mutacji). */
  security?: "orderToken" | "session";
  /** Minimalna rola trasy admina (docs/16 par. 1.2). */
  role?: Role;
}

/** B-003: naglowek CSRF wymagany przy kazdej mutacji admina (dokladany w builderze). */
export const CSRF_HEADER: HeaderDoc = {
  name: "X-CSRF-Token",
  required: true,
  description: "Token CSRF zwrocony w csrf_token odpowiedzi logowania lub GET /v1/admin/auth/me.",
};

const IF_MATCH: HeaderDoc = {
  name: "If-Match",
  required: true,
  description:
    'Wersja zasobu z ostatniego odczytu, w cudzyslowie ("3"); niezgodnosc = 412 conflict, brak = 428.',
};

const ORDER_TOKEN: HeaderDoc = {
  name: "X-Order-Token",
  required: true,
  description:
    "Token zamowienia zwrocony w POST /v1/orders (lista zamowien przyjmuje kilka tokenow po przecinku).",
};

export const ROUTES: RouteDoc[] = [
  {
    method: "get",
    path: "/health",
    summary: "Liveness",
    tag: "health",
    ids: ["B-230"],
    success: { status: 200, description: "Proces zyje." },
  },
  {
    method: "get",
    path: "/health/ready",
    summary: "Readiness: baza, migracje, kolejka outbox",
    tag: "health",
    ids: ["B-230"],
    success: { status: 200, description: "Gotowe do ruchu." },
    errors: [{ status: 503, code: "internal_error" }],
  },
  {
    method: "get",
    path: "/ready",
    summary: "Readiness (alias /health/ready)",
    tag: "health",
    ids: ["B-230"],
    success: { status: 200, description: "Gotowe do ruchu." },
    errors: [{ status: 503, code: "internal_error" }],
  },
  {
    method: "get",
    path: "/v1/categories",
    summary: "Kategorie z liczba modeli i cena od",
    tag: "katalog",
    ids: ["F-020", "F-002"],
    success: { status: 200, schema: categoriesResponseSchema, description: "Kategorie." },
  },
  {
    method: "get",
    path: "/v1/products",
    summary: "Lista produktow kategorii z filtrami, sortowaniem i kursorem",
    tag: "katalog",
    ids: ["F-020", "F-021", "F-022", "F-023", "F-024", "F-025", "F-026"],
    query: listingQuerySchema,
    success: { status: 200, schema: listingResponseSchema, description: "Strona listingu." },
    errors: [{ status: 404, code: "not_found" }],
  },
  {
    method: "get",
    path: "/v1/products/{slug}",
    summary: "Pelny produkt (?sku= wybiera wariant)",
    tag: "katalog",
    ids: ["F-060", "F-078"],
    pathParams: { slug: "Slug produktu, np. granit-tkl" },
    query: productQuerySchema,
    success: { status: 200, schema: productSchema, description: "Produkt." },
    errors: [{ status: 404, code: "not_found" }],
  },
  {
    method: "get",
    path: "/v1/products/{slug}/complete-set",
    summary: "Propozycja Dokoncz set",
    tag: "katalog",
    ids: ["F-069"],
    pathParams: { slug: "Slug produktu" },
    query: completeSetQuerySchema,
    success: {
      status: 200,
      schema: completeSetResponseSchema,
      description: "Set z cena po rabacie.",
    },
    errors: [{ status: 404, code: "not_found" }],
  },
  {
    method: "get",
    path: "/v1/facets",
    summary: "Facety kategorii z licznikami",
    tag: "katalog",
    ids: ["F-021", "F-029"],
    query: facetsQuerySchema,
    success: { status: 200, schema: facetsResponseSchema, description: "Facety." },
    errors: [{ status: 404, code: "not_found" }],
  },
  {
    method: "get",
    path: "/v1/search",
    summary: "Wyszukiwanie produktow, kategorii i poradnikow",
    tag: "katalog",
    ids: ["F-005", "F-006", "F-007"],
    query: searchQuerySchema,
    success: { status: 200, schema: searchResponseSchema, description: "Wyniki." },
  },
  {
    method: "get",
    path: "/v1/switches",
    summary: "Przelaczniki",
    tag: "slowniki",
    ids: ["F-062", "F-074"],
    success: { status: 200, schema: switchesResponseSchema, description: "Przelaczniki." },
  },
  {
    method: "get",
    path: "/v1/colors",
    summary: "Kolory z probkami",
    tag: "slowniki",
    ids: ["F-062", "F-115"],
    success: { status: 200, schema: colorsResponseSchema, description: "Kolory." },
  },
  {
    method: "get",
    path: "/v1/rules",
    summary: "Profile i reguly dopasowania",
    tag: "slowniki",
    ids: ["F-101", "F-104"],
    success: { status: 200, schema: rulesSchema, description: "Reguly." },
  },
  {
    method: "get",
    path: "/v1/presets",
    summary: "Gotowe sety z cena liczona na biezaco",
    tag: "katalog",
    ids: ["F-111"],
    success: { status: 200, schema: presetsResponseSchema, description: "Presety." },
  },
  {
    method: "get",
    path: "/v1/shop-settings",
    summary: "Ustawienia publiczne sklepu",
    tag: "ustawienia",
    ids: ["F-001", "F-009", "F-073", "F-153"],
    success: { status: 200, schema: publicShopSettingsSchema, description: "Ustawienia." },
  },
  {
    method: "get",
    path: "/v1/shipping-estimate",
    summary: "Termin wysylki i dostawy",
    tag: "ustawienia",
    ids: ["F-065"],
    query: shippingEstimateQuerySchema,
    success: { status: 200, schema: shippingEstimateResponseSchema, description: "Termin." },
    errors: [{ status: 404, code: "not_found" }],
  },
  {
    method: "get",
    path: "/v1/pickup-points",
    summary: "Punkty odbioru",
    tag: "ustawienia",
    ids: ["F-172"],
    query: pickupPointsQuerySchema,
    success: { status: 200, schema: pickupPointsResponseSchema, description: "Punkty." },
  },
  {
    method: "post",
    path: "/v1/cart/quote",
    summary: "Wycena koszyka bez cache",
    tag: "koszyk",
    ids: ["F-150", "F-151", "F-152", "F-153", "F-154", "F-155", "F-156", "F-157", "F-024"],
    body: quoteRequestSchema,
    success: { status: 200, schema: quoteResponseSchema, description: "Wycena." },
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/orders",
    summary: "Utworzenie zamowienia pending_payment",
    tag: "zamowienia",
    ids: ["F-170", "F-171", "F-172", "F-173", "F-174", "F-175", "F-176", "F-180"],
    body: orderRequestSchema,
    headers: [
      {
        name: "Idempotency-Key",
        required: true,
        description: "UUID; ten sam klucz i cialo = ta sama odpowiedz (24 h).",
      },
    ],
    success: { status: 201, schema: orderCreatedSchema, description: "Zamowienie utworzone." },
    errors: [{ status: 409, code: "out_of_stock | price_changed | idempotency_conflict" }],
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/orders",
    summary: "Lista zamowien dla konta demo",
    tag: "zamowienia",
    ids: ["F-201", "F-202"],
    headers: [ORDER_TOKEN],
    success: {
      status: 200,
      schema: orderListSchema,
      description: "Zamowienia wlascicieli tokenow.",
    },
    errors: [{ status: 401, code: "unauthorized" }],
    noStore: true,
    security: "orderToken",
  },
  {
    method: "get",
    path: "/v1/orders/{number}",
    summary: "Odczyt zamowienia wlasciciela tokenu",
    tag: "zamowienia",
    ids: ["F-178", "F-202"],
    pathParams: { number: "Numer TK-RRMMDD-XXXX" },
    headers: [ORDER_TOKEN],
    success: { status: 200, schema: orderDetailSchema, description: "Zamowienie." },
    errors: [
      { status: 401, code: "unauthorized" },
      { status: 404, code: "not_found" },
    ],
    noStore: true,
    security: "orderToken",
  },
  {
    method: "post",
    path: "/v1/orders/{number}/payment/simulate",
    summary: "Symulacja platnosci (paid | failed)",
    tag: "zamowienia",
    ids: ["F-177", "F-178", "F-179"],
    pathParams: { number: "Numer TK-RRMMDD-XXXX" },
    headers: [ORDER_TOKEN],
    body: paymentSimulateRequestSchema,
    success: {
      status: 200,
      schema: paymentSimulateResponseSchema,
      description: "Wynik symulacji.",
    },
    errors: [
      { status: 404, code: "not_found" },
      { status: 409, code: "invalid_transition | out_of_stock" },
    ],
    noStore: true,
    security: "orderToken",
  },

  // ---- B-001..B-013 (TAKTYL-45): uwierzytelnianie, uzytkownicy, dziennik zmian --------------------------------------
  {
    method: "post",
    path: "/v1/admin/auth/login",
    summary: "Logowanie e-mailem i haslem (ustawia ciasteczko sesji)",
    tag: "admin: sesja",
    ids: ["B-001", "B-002", "B-004"],
    body: loginRequestSchema,
    success: { status: 200, schema: sessionResponseSchema, description: "Sesja i token CSRF." },
    errors: [
      { status: 401, code: "unauthorized (jednolity komunikat)" },
      { status: 429, code: "rate_limited (blokada po 5 probach, Retry-After)" },
    ],
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/auth/demo-viewer",
    summary: "Sesja roli viewer bez hasla (tylko DEMO_MODE=true)",
    tag: "admin: sesja",
    ids: ["B-007"],
    success: { status: 200, schema: sessionResponseSchema, description: "Sesja viewer." },
    errors: [{ status: 404, code: "not_found (gdy tryb demo wylaczony)" }],
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/auth/logout",
    summary: "Wylogowanie (uniewaznienie sesji po stronie serwera)",
    tag: "admin: sesja",
    ids: ["B-009"],
    success: { status: 204, description: "Sesja zakonczona." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/auth/me",
    summary: "Biezacy uzytkownik, rola i token CSRF",
    tag: "admin: sesja",
    ids: ["B-001"],
    success: { status: 200, schema: sessionResponseSchema, description: "Sesja." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/auth/session",
    summary: "Alias GET /v1/admin/auth/me",
    tag: "admin: sesja",
    ids: ["B-001"],
    success: { status: 200, schema: sessionResponseSchema, description: "Sesja." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/users",
    summary: "Lista kont backpanelu",
    tag: "admin: uzytkownicy",
    ids: ["B-013"],
    success: { status: 200, schema: usersResponseSchema, description: "Konta." },
    security: "session",
    role: "owner",
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/users",
    summary: "Nowe konto (owner, editor lub viewer z haslem poczatkowym)",
    tag: "admin: uzytkownicy",
    ids: ["B-013"],
    body: createUserRequestSchema,
    success: { status: 201, schema: adminUserSchema, description: "Konto utworzone." },
    errors: [{ status: 409, code: "conflict (duplikat e-maila)" }],
    security: "session",
    role: "owner",
    noStore: true,
  },
  {
    method: "patch",
    path: "/v1/admin/users/{id}",
    summary: "Zmiana roli, dezaktywacja, reset hasla (haslo tymczasowe zwracane raz)",
    tag: "admin: uzytkownicy",
    ids: ["B-013"],
    pathParams: { id: "Identyfikator konta" },
    body: updateUserRequestSchema,
    success: { status: 200, schema: updateUserResponseSchema, description: "Konto po zmianie." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 409, code: "conflict (ostatni owner)" },
    ],
    security: "session",
    role: "owner",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/audit",
    summary: "Dziennik zmian z filtrami (uzytkownik, encja, zakres dat); viewer bez pol osobowych",
    tag: "admin: dziennik",
    ids: ["B-011", "B-012"],
    query: auditListQuerySchema,
    success: { status: 200, schema: auditListSchema, description: "Strona dziennika." },
    security: "session",
    role: "viewer",
    noStore: true,
  },

  // ---- B-200..B-205, B-208 (TAKTYL-48): zamowienia w backpanelu ------------------------------------------------------
  {
    method: "get",
    path: "/v1/admin/orders",
    summary:
      "Lista zamowien z filtrami (status, data, numer, platnosc, dostawa); e-mail zawsze zamaskowany",
    tag: "admin: zamowienia",
    ids: ["B-200", "B-201"],
    query: adminOrderListQuerySchema,
    success: { status: 200, schema: adminOrderListSchema, description: "Strona zamowien." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/orders/{number}",
    summary: "Szczegoly zamowienia (viewer: dane osobowe zamaskowane w odpowiedzi)",
    tag: "admin: zamowienia",
    ids: ["B-202", "B-208"],
    pathParams: { number: "Numer TK-RRMMDD-XXXX" },
    success: { status: 200, schema: adminOrderDetailSchema, description: "Zamowienie." },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/orders/{number}/transition",
    summary: "Zmiana statusu wg maszyny stanow (anulowanie wymaga powodu i zwraca stany)",
    tag: "admin: zamowienia",
    ids: ["B-203", "B-205"],
    pathParams: { number: "Numer TK-RRMMDD-XXXX" },
    body: orderTransitionRequestSchema,
    success: { status: 200, schema: adminOrderDetailSchema, description: "Zamowienie po zmianie." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 409, code: "invalid_transition" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/orders/{number}/note",
    summary: "Notatka wewnetrzna do zamowienia",
    tag: "admin: zamowienia",
    ids: ["B-204"],
    pathParams: { number: "Numer TK-RRMMDD-XXXX" },
    body: orderNoteRequestSchema,
    success: { status: 201, schema: adminOrderDetailSchema, description: "Zamowienie z notatka." },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "editor",
    noStore: true,
  },

  // ---- B-060, B-061 (TAKTYL-46): propagacja zmian ------------------------------------------------------------------
  {
    method: "post",
    path: "/v1/admin/revalidate",
    summary: "Reczna rewalidacja znacznikow (diagnostyka); znaczniki trafiaja do outbox",
    tag: "admin: propagacja",
    ids: ["B-061"],
    body: revalidateRequestSchema,
    success: {
      status: 202,
      schema: revalidateResponseSchema,
      description: "Znaczniki zakolejkowane.",
    },
    security: "session",
    role: "owner",
    noStore: true,
  },

  // ---- B-100..B-115 (TAKTYL-47): katalog w backpanelu --------------------------------------------------------------
  {
    method: "get",
    path: "/v1/admin/products",
    summary: "Lista produktow z filtrami, szukaniem i sortowaniem",
    tag: "admin: katalog",
    ids: ["B-100", "B-101"],
    query: adminProductListQuerySchema,
    success: { status: 200, schema: adminProductListSchema, description: "Strona produktow." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/products/{id}",
    summary: "Produkt z wariantami, stanami, zdjeciami; ETag = wersja",
    tag: "admin: katalog",
    ids: ["B-102", "B-105"],
    pathParams: { id: "Identyfikator produktu, np. m-wrobel" },
    success: { status: 200, schema: adminProductDetailSchema, description: "Produkt." },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/products",
    summary: "Nowy produkt (atrybuty wg kategorii); bez wariantow zostaje ukryty (archived)",
    tag: "admin: katalog",
    ids: ["B-111"],
    body: productCreateSchema,
    success: { status: 201, schema: adminProductDetailSchema, description: "Produkt utworzony." },
    errors: [{ status: 409, code: "conflict (zajety slug lub id)" }],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "patch",
    path: "/v1/admin/products/{id}",
    summary: "Edycja produktu: nazwa, slug, short, atrybuty, plakietki, fit, in_box, gpsr, status",
    tag: "admin: katalog",
    ids: ["B-102", "B-109", "B-110"],
    pathParams: { id: "Identyfikator produktu, np. m-wrobel" },
    body: productPatchSchema,
    headers: [IF_MATCH],
    success: {
      status: 200,
      schema: adminProductDetailSchema,
      description: "Produkt po zmianie (ostrzezenia w warnings).",
    },
    errors: [
      { status: 404, code: "not_found" },
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
      { status: 428, code: "validation_failed (brak If-Match)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "delete",
    path: "/v1/admin/products/{id}",
    summary: "Twarde usuniecie produktu tylko bez zamowien i setow",
    tag: "admin: katalog",
    ids: ["B-110"],
    pathParams: { id: "Identyfikator produktu, np. m-wrobel" },
    success: { status: 204, description: "Usunieto." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 409, code: "conflict (ma zamowienia lub jest w secie)" },
    ],
    security: "session",
    role: "owner",
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/products/{id}/variants",
    summary: "Nowy wariant (SKU wg wzoru kategorii i kodow)",
    tag: "admin: katalog",
    ids: ["B-111", "B-103"],
    pathParams: { id: "Identyfikator produktu, np. m-wrobel" },
    body: variantCreateSchema,
    success: {
      status: 201,
      schema: adminProductDetailSchema,
      description: "Produkt z nowym wariantem.",
    },
    errors: [
      { status: 404, code: "not_found" },
      { status: 409, code: "conflict (zajety SKU lub kombinacja)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "patch",
    path: "/v1/admin/variants/{sku}",
    summary:
      "Edycja wariantu: kolor, przelacznik, rozmiar, klucz zdjec, dostepnosc (If-Match = wersja wariantu)",
    tag: "admin: katalog",
    ids: ["B-103", "B-109"],
    pathParams: { sku: "SKU wariantu, np. M-WRB-GRF" },
    body: variantPatchSchema,
    headers: [IF_MATCH],
    success: {
      status: 200,
      schema: adminProductDetailSchema,
      description: "Produkt po zmianie wariantu.",
    },
    errors: [
      { status: 404, code: "not_found" },
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
      { status: 428, code: "validation_failed (brak If-Match)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "delete",
    path: "/v1/admin/variants/{sku}",
    summary: "Twarde usuniecie wariantu tylko bez zamowien i setow",
    tag: "admin: katalog",
    ids: ["B-110"],
    pathParams: { sku: "SKU wariantu, np. M-WRB-GRF" },
    success: { status: 204, description: "Usunieto." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 409, code: "conflict (ma zamowienia lub jest w secie)" },
    ],
    security: "session",
    role: "owner",
    noStore: true,
  },
  {
    method: "put",
    path: "/v1/admin/variants/{sku}/price",
    summary: "Nowa cena: dopisuje wiersz price_history; lowest_30d wylicza serwer",
    tag: "admin: katalog",
    ids: ["B-104", "B-106", "B-107"],
    pathParams: { sku: "SKU wariantu, np. M-WRB-GRF" },
    body: setPriceRequestSchema,
    headers: [{ ...IF_MATCH, required: false }],
    success: {
      status: 200,
      schema: adminProductDetailSchema,
      description: "Produkt z nowa cena i przeliczonym lowest_30d_gr.",
    },
    errors: [
      { status: 404, code: "not_found" },
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/variants/{sku}/price-history",
    summary: "Historia cen, wyliczone lowest_30d i okno obliczenia (tylko do odczytu)",
    tag: "admin: katalog",
    ids: ["B-105"],
    pathParams: { sku: "SKU wariantu, np. M-WRB-GRF" },
    success: { status: 200, schema: priceHistoryResponseSchema, description: "Historia cen." },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "put",
    path: "/v1/admin/variants/{sku}/stock",
    summary: "Ustawienie stanu z ruchem magazynowym (adjustment)",
    tag: "admin: katalog",
    ids: ["B-108"],
    pathParams: { sku: "SKU wariantu, np. M-WRB-GRF" },
    body: setStockRequestSchema,
    headers: [{ ...IF_MATCH, required: false }],
    success: {
      status: 200,
      schema: adminProductDetailSchema,
      description: "Produkt po zmianie stanu.",
    },
    errors: [
      { status: 404, code: "not_found" },
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/variants/{sku}/stock-movements",
    summary: "Historia ruchow magazynowych wariantu",
    tag: "admin: katalog",
    ids: ["B-108"],
    pathParams: { sku: "SKU wariantu, np. M-WRB-GRF" },
    success: {
      status: 200,
      schema: stockMovementsResponseSchema,
      description: "Ruchy magazynowe.",
    },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/presets",
    summary: "Gotowe sety z cena liczona na biezaco i wersja",
    tag: "admin: katalog",
    ids: ["B-114"],
    success: { status: 200, schema: adminPresetsResponseSchema, description: "Sety." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "put",
    path: "/v1/admin/presets/{id}",
    summary: "Edycja gotowego setu (3 SKU, nazwa, profil, notatka); cena liczona, nie edytowalna",
    tag: "admin: katalog",
    ids: ["B-114"],
    pathParams: { id: "Identyfikator setu, np. programista" },
    body: presetUpdateSchema,
    headers: [IF_MATCH],
    success: { status: 200, schema: adminPresetSchema, description: "Set po zmianie." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
      { status: 428, code: "validation_failed (brak If-Match)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },

  // ---- B-400..B-408 (TAKTYL-49): ustawienia sklepu ------------------------------------------------------------------
  {
    method: "get",
    path: "/v1/admin/settings",
    summary:
      "Pelne ustawienia sklepu (takze nieaktywne metody, kody, punkty odbioru); ETag = wersja",
    tag: "admin: ustawienia",
    ids: ["B-400", "B-401", "B-402", "B-403", "B-404", "B-405", "B-406", "B-407", "B-408"],
    success: { status: 200, schema: adminSettingsSchema, description: "Ustawienia." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "patch",
    path: "/v1/admin/settings",
    summary:
      "Zmiana ustawien (tylko owner): prog dostawy, rabat setu, metody dostawy i platnosci, kody, punkty odbioru, etykieta demo, godzina wysylki, dane firmy",
    tag: "admin: ustawienia",
    ids: ["B-400", "B-401", "B-402", "B-403", "B-404", "B-405", "B-406", "B-407", "B-408"],
    body: settingsPatchSchema,
    headers: [IF_MATCH],
    success: { status: 200, schema: adminSettingsSchema, description: "Ustawienia po zmianie." },
    errors: [
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
      { status: 428, code: "validation_failed (brak If-Match)" },
      {
        status: 422,
        code: "validation_failed (zakres, spojnosc, kody, etykieta demo, dane firmy)",
      },
    ],
    security: "session",
    role: "owner",
    noStore: true,
  },

  // ---- B-300..B-309 (TAKTYL-61): tresci, opisy, opinie, zgloszenia ----------------------------------------------------
  {
    method: "get",
    path: "/v1/admin/content",
    summary: "Lista stron, artykulow poradnika (filtr typu)",
    tag: "admin: tresci",
    ids: ["B-304", "B-305"],
    query: adminContentListQuerySchema,
    success: { status: 200, schema: adminContentListSchema, description: "Tresci." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/content/{id}",
    summary: "Pojedyncza tresc; ETag = wersja",
    tag: "admin: tresci",
    ids: ["B-304", "B-305"],
    pathParams: { id: "Identyfikator tresci (cuid)" },
    success: { status: 200, schema: adminContentResponseSchema, description: "Tresc." },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "post",
    path: "/v1/admin/content",
    summary: "Nowa strona lub artykul (Markdown ograniczony, sanityzowany allowlista)",
    tag: "admin: tresci",
    ids: ["B-304", "B-305", "B-306"],
    body: contentCreateSchema,
    success: {
      status: 201,
      schema: adminContentResponseSchema,
      description: "Tresc utworzona (ostrzezenia w warnings).",
    },
    errors: [
      { status: 409, code: "conflict (zajety slug)" },
      { status: 422, code: "validation_failed (tresc prawna, marka, profil artykulu)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "patch",
    path: "/v1/admin/content/{id}",
    summary: "Edycja, publikacja, cofniecie do szkicu; naglowek demo jest nieusuwalny",
    tag: "admin: tresci",
    ids: ["B-304", "B-305", "B-306"],
    pathParams: { id: "Identyfikator tresci (cuid)" },
    body: contentPatchSchema,
    headers: [IF_MATCH],
    success: { status: 200, schema: adminContentResponseSchema, description: "Tresc po zmianie." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
      { status: 428, code: "validation_failed (brak If-Match)" },
      { status: 422, code: "validation_failed" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "delete",
    path: "/v1/admin/content/{id}",
    summary: "Usuniecie artykulu (strony informacyjne i prawne tylko archiwizacja)",
    tag: "admin: tresci",
    ids: ["B-305"],
    pathParams: { id: "Identyfikator tresci (cuid)" },
    success: { status: 204, description: "Usunieto." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 409, code: "conflict (strona systemowa)" },
    ],
    security: "session",
    role: "owner",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/faq",
    summary: "FAQ w kolejnosci (takze szkice)",
    tag: "admin: tresci",
    ids: ["B-307"],
    success: { status: 200, schema: adminFaqSchema, description: "Pytania." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "put",
    path: "/v1/admin/faq",
    summary: "Zapis calej uporzadkowanej listy FAQ (dodaje, zmienia, usuwa pominiete)",
    tag: "admin: tresci",
    ids: ["B-307"],
    body: faqPutSchema,
    success: { status: 200, schema: adminFaqSchema, description: "Lista po zapisie." },
    errors: [{ status: 422, code: "validation_failed" }],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "put",
    path: "/v1/admin/products/{id}/description",
    summary: "Opis produktu; zakazane slowa i dlugosc 60-120 slow to ostrzezenia",
    tag: "admin: tresci",
    ids: ["B-300", "B-301"],
    pathParams: { id: "Identyfikator produktu, np. m-wrobel" },
    body: descriptionPutSchema,
    headers: [IF_MATCH],
    success: {
      status: 200,
      schema: descriptionResponseSchema,
      description: "Opis zapisany (ostrzezenia w warnings).",
    },
    errors: [
      { status: 404, code: "not_found" },
      { status: 412, code: "conflict (If-Match: wersja zasobu zmienila sie)" },
      { status: 428, code: "validation_failed (brak If-Match)" },
      { status: 422, code: "validation_failed (marka)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/reviews",
    summary: "Opinie demo pogrupowane po produkcie; stala etykieta sekcji",
    tag: "admin: tresci",
    ids: ["B-302", "B-303"],
    query: adminReviewListQuerySchema,
    success: { status: 200, schema: adminReviewListSchema, description: "Opinie." },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "put",
    path: "/v1/admin/products/{id}/reviews",
    summary: "Zestaw opinii demo produktu (3-6, oceny 3-5, demo wymuszone)",
    tag: "admin: tresci",
    ids: ["B-302"],
    pathParams: { id: "Identyfikator produktu, np. m-wrobel" },
    body: reviewsPutSchema,
    success: { status: 200, schema: adminProductReviewsSchema, description: "Opinie produktu." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 422, code: "validation_failed" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "get",
    path: "/v1/admin/messages",
    summary: "Zgloszenia z formularzy kontaktu i newslettera; viewer widzi dane zamaskowane",
    tag: "admin: tresci",
    ids: ["B-308"],
    query: adminMessageListQuerySchema,
    success: { status: 200, schema: adminMessageListSchema, description: "Zgloszenia." },
    security: "session",
    role: "viewer",
    noStore: true,
  },
  {
    method: "patch",
    path: "/v1/admin/messages/{id}",
    summary: "Oznaczenie wiadomosci kontaktowej jako obsluzonej",
    tag: "admin: tresci",
    ids: ["B-308"],
    pathParams: { id: "Identyfikator zgloszenia" },
    body: messagePatchSchema,
    success: { status: 204, description: "Zapisano." },
    errors: [
      { status: 404, code: "not_found" },
      { status: 422, code: "validation_failed (zapis newslettera nie ma statusu)" },
    ],
    security: "session",
    role: "editor",
    noStore: true,
  },
  {
    method: "delete",
    path: "/v1/admin/messages/{id}",
    summary: "Usuniecie zgloszenia (RODO w demo)",
    tag: "admin: tresci",
    ids: ["B-309"],
    pathParams: { id: "Identyfikator zgloszenia" },
    success: { status: 204, description: "Usunieto." },
    errors: [{ status: 404, code: "not_found" }],
    security: "session",
    role: "owner",
    noStore: true,
  },
];
